# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geradordecpf.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 309)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 170, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.retorno = QtWidgets.QLineEdit(self.centralwidget)
        self.retorno.setGeometry(QtCore.QRect(10, 220, 271, 41))
        self.retorno.setStyleSheet("")
        self.retorno.setText("")
        self.retorno.setAlignment(QtCore.Qt.AlignCenter)
        self.retorno.setReadOnly(True)
        self.retorno.setObjectName("retorno")
        self.btValida = QtWidgets.QPushButton(self.centralwidget)
        self.btValida.setGeometry(QtCore.QRect(100, 270, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btValida.setFont(font)
        self.btValida.setObjectName("btValida")
        self.btGera = QtWidgets.QPushButton(self.centralwidget)
        self.btGera.setGeometry(QtCore.QRect(10, 49, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btGera.setFont(font)
        self.btGera.setObjectName("btGera")
        self.retornoGera = QtWidgets.QLineEdit(self.centralwidget)
        self.retornoGera.setGeometry(QtCore.QRect(10, 90, 271, 41))
        self.retornoGera.setText("")
        self.retornoGera.setAlignment(QtCore.Qt.AlignCenter)
        self.retornoGera.setReadOnly(False)
        self.retornoGera.setObjectName("retornoGera")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerador de CPF"))
        self.label.setText(_translate("MainWindow", "Validando o CPF"))
        self.btValida.setText(_translate("MainWindow", "Validar"))
        self.btGera.setText(_translate("MainWindow", "Gerar"))
        self.label_2.setText(_translate("MainWindow", "Digite um CPF ou clique em Gerar"))
